### ISSUE TITLE
LVFS is temporarily offline

### ISSUE THREAD

**Issue by daenney** [hughsie/lvfs-website#95] opened 2018-03-30 11:33 UTC
For some reason I'm currently unable to download the latest Dell firmware for an XPS 9360:

```
Downloading 0.2.6.2 for XPS 13 9360 System Firmware...
Fetching firmware https://fwupd.org/downloads/cddd4fbfb52ded7f300780973d751b2c12c0fe65-Signed_1152921504627521618.cab

Failed to download https://fwupd.org/downloads/cddd4fbfb52ded7f300780973d751b2c12c0fe65-Signed_1152921504627521618.cab: Bad Gateway
```

Initially looking at the error message it presents as LVFS being temporarily offline:
```
    <div class="container mt-3">
      <div class="container mt-3">
        <div class="alert alert-warning" role="alert">
          The LVFS is temporarily unavailable and should be back soon.
        </div>
      </div>
    </div>
```

However, as @superm1 pointed out, LVFS is online, but this particular firmware link is behaving strangely/presenting as being offline. This is related to hughsie/fwupd#451.

**Comment by hughsie** [comment] 2018-03-30 12:15
All the firmware downloads have been failing since midnight; investigating now.

**Comment by hughsie** [comment] 2018-03-30 12:17
MariaDB [lvfs]> SELECT * FROM analytics ORDER BY datestr DESC LIMIT 10;
    +----------+------+
    | datestr  | cnt  |
    +----------+------+
    | 20180330 |    1 |
    | 20180330 |    1 |
    | 20180329 | 7417 |
    | 20180328 | 7393 |
    | 20180327 | 4712 |
    | 20180326 | 4763 |
    | 20180325 | 4264 |
    | 20180324 | 4142 |
    | 20180323 | 4662 |
    | 20180322 | 4995 |

**Comment by hughsie** [comment] 2018-03-30 12:19
I've deleted the duplicate key. Downloads now work, but I'm investigating the root cause.

**Comment by hughsie** [comment] 2018-03-30 12:33
Some initial notes: `datestr` is an indexed primary key, but was not marked as unique. I've fixed this, which will prevent duplicate primary keys being inserted. It won't however fix the race. I'll do some research today.

**Comment by hughsie** [comment] 2018-03-30 18:44
So, root cause analysis. There's a ~1ms race in checking for a existing `Analytic` item and creating one if not. Given we serve a firmware every few seconds, and we've served over 1 million firmware files I'm somewhat surprised we've not hit this before.

**Closed** 2018-03-30 20:05 UTC
Labels: bug

**Comment by daenney** [comment] 2018-03-31 09:55
Thank you for the super quick response and fix!
